# ê¸°ë³¸ ì‚¬ì´íŠ¸ ì„¤ì •
title: "ê²€ë¼ì œì˜ ë…¸íŠ¸"   # ì‚¬ì´íŠ¸ ì œëª©
description: "ë¨¸ì‹ ëŸ¬ë‹, ì¸ê³µì§€ëŠ¥, ğŸ¸, ğŸ¸"   # ì‚¬ì´íŠ¸ ì„¤ëª…
baseurl: "/blog"   # ë£¨íŠ¸ê°€ ì•„ë‹Œ í•˜ìœ„ ë””ë ‰í† ë¦¬ì— ìˆì„ ê²½ìš° ê²½ë¡œë¥¼ ì§€ì • (ì˜ˆ: /blog)
url: "http://yourdomain.com"   # ì‚¬ì´íŠ¸ì˜ URL

# í…Œë§ˆ ì„¤ì •
theme: jekyll-theme-hydejack   # ì‚¬ìš©í•  Jekyll í…Œë§ˆ (Hydejack)

# ë¹Œë“œ ì„¤ì •
markdown: kramdown   # ì‚¬ìš©ëœ ë§ˆí¬ë‹¤ìš´ ë³€í™˜ê¸° (ê¸°ë³¸ê°’: kramdown)
highlighter: rouge   # ì½”ë“œ í•˜ì´ë¼ì´í„° ì„¤ì • (ê¸°ë³¸ê°’: rouge)

# í”ŒëŸ¬ê·¸ì¸ ì„¤ì •
plugins:
  - jekyll-include-cache   # í•„ìš”í•œ í”ŒëŸ¬ê·¸ì¸ ì¶”ê°€

# ê¸°íƒ€ ì„¤ì •
permalink: /:categories/:title/   # URL êµ¬ì¡° ì„¤ì •
paginate: 10   # í•œ í˜ì´ì§€ì— í‘œì‹œë  í¬ìŠ¤íŠ¸ ìˆ˜

# Hydejack ì„¤ì •
advertise: False

menu:
  - title: Github Page
    url:   /github_page/

collections:
  blog:
    output: true

plugins:
  - jekyll-paginate